<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Melanie Beebe">

<title>ST558 Homework 5</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="fullcontent">

<div id="quarto-search-results"></div>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">ST558 Homework 5</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Melanie Beebe </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="task-1.-conceptual-questions" class="level1">
<h1>Task 1. Conceptual Questions</h1>
<ol type="1">
<li><p>What is the purpose of using cross-validation when fitting a random forest model?</p>
<blockquote class="blockquote">
<p>The purpose of cross validation is to help identify the optimal the number of variables/predictors to use for each split.</p>
</blockquote></li>
<li><p>Describe the bagged tree algorithm.</p>
<blockquote class="blockquote">
<p>The bagged tree algorithm uses one set of data/sample and treats it as a population. Samples (called bootstrap samples, resampling done with replacement) are taken from the data and a tree constructed for each bootstrap sample. If the method is for regression trees, the resulting predictions averaged. For classification trees, often majority vote is used to determine the final classification prediction.</p>
</blockquote></li>
<li><p>What is meant by a general linear model?</p>
<blockquote class="blockquote">
<p>The term general linear model typically refers to linear regression, where the response is continuous and both continuous and categorical predictors can be included.</p>
</blockquote></li>
<li><p>When fitting a multiple linear regression model, what does adding an interaction term do? That is, what does it allow the model to do differently as compared to when it is not included in the model?</p>
<blockquote class="blockquote">
<p>Interaction terms allow the effect of one predictor on the response variable to be dependent on the effect of another predictor. This affects the resulting coefficients in the model and our interpretation of them. In MLR without interactions, the best plane is being fit to the data. In MLR with interactions, the best saddle through the points is being fit.</p>
</blockquote></li>
<li><p>Why do we split our data into a training and test set?</p>
<blockquote class="blockquote">
<p>The training set is used to train the model we are interested in. The test set is used to test the prediction accuracy of the model. By having separate sets for training and testing, the resulting predictions are less biased and more accurate representations of the model since the test data is unseen during the training process.</p>
</blockquote></li>
</ol>
</section>
<section id="task-2.-fitting-models" class="level1">
<h1>Task 2. Fitting Models</h1>
<p>The first step is to read in the data. Since it is a csv file, we can use read_csv() from tidyverse. Packages used throughout this document will also be loaded in this step.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psych)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caret)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>heart_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"heart.csv"</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>heart_data</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 918 × 12
     Age Sex   ChestPainType RestingBP Cholesterol FastingBS RestingECG MaxHR
   &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;             &lt;dbl&gt;       &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;      &lt;dbl&gt;
 1    40 M     ATA                 140         289         0 Normal       172
 2    49 F     NAP                 160         180         0 Normal       156
 3    37 M     ATA                 130         283         0 ST            98
 4    48 F     ASY                 138         214         0 Normal       108
 5    54 M     NAP                 150         195         0 Normal       122
 6    39 M     NAP                 120         339         0 Normal       170
 7    45 F     ATA                 130         237         0 Normal       170
 8    54 M     ATA                 110         208         0 Normal       142
 9    37 M     ASY                 140         207         0 Normal       130
10    48 F     ATA                 120         284         0 Normal       120
# ℹ 908 more rows
# ℹ 4 more variables: ExerciseAngina &lt;chr&gt;, Oldpeak &lt;dbl&gt;, ST_Slope &lt;chr&gt;,
#   HeartDisease &lt;dbl&gt;</code></pre>
</div>
</div>
<section id="quick-edadata-preparation" class="level2">
<h2 class="anchored" data-anchor-id="quick-edadata-preparation">Quick EDA/Data Preparation</h2>
<section id="understand-the-data." class="level3">
<h3 class="anchored" data-anchor-id="understand-the-data.">1. Understand the data.</h3>
<p>The first step is to understand the data by checking missingness and summarize the data. First, missingness will be checked using is.na(). This check shows that there is no missing data in terms of NA values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colSums</span>(<span class="fu">is.na</span>(heart_data))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           Age            Sex  ChestPainType      RestingBP    Cholesterol 
             0              0              0              0              0 
     FastingBS     RestingECG          MaxHR ExerciseAngina        Oldpeak 
             0              0              0              0              0 
      ST_Slope   HeartDisease 
             0              0 </code></pre>
</div>
</div>
<p>Next, we can summarize the data. The simplest method is to use describe() from the psych package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">describe</span>(heart_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                vars   n   mean     sd median trimmed   mad  min   max range
Age                1 918  53.51   9.43   54.0   53.71 10.38 28.0  77.0  49.0
Sex*               2 918   1.79   0.41    2.0    1.86  0.00  1.0   2.0   1.0
ChestPainType*     3 918   1.78   0.96    1.0    1.66  0.00  1.0   4.0   3.0
RestingBP          4 918 132.40  18.51  130.0  131.50 14.83  0.0 200.0 200.0
Cholesterol        5 918 198.80 109.38  223.0  204.41 68.20  0.0 603.0 603.0
FastingBS          6 918   0.23   0.42    0.0    0.17  0.00  0.0   1.0   1.0
RestingECG*        7 918   1.99   0.63    2.0    1.99  0.00  1.0   3.0   2.0
MaxHR              8 918 136.81  25.46  138.0  137.23 26.69 60.0 202.0 142.0
ExerciseAngina*    9 918   1.40   0.49    1.0    1.38  0.00  1.0   2.0   1.0
Oldpeak           10 918   0.89   1.07    0.6    0.74  0.89 -2.6   6.2   8.8
ST_Slope*         11 918   2.36   0.61    2.0    2.41  0.00  1.0   3.0   2.0
HeartDisease      12 918   0.55   0.50    1.0    0.57  0.00  0.0   1.0   1.0
                 skew kurtosis   se
Age             -0.20    -0.40 0.31
Sex*            -1.42     0.02 0.01
ChestPainType*   0.79    -0.72 0.03
RestingBP        0.18     3.23 0.61
Cholesterol     -0.61     0.10 3.61
FastingBS        1.26    -0.41 0.01
RestingECG*      0.01    -0.50 0.02
MaxHR           -0.14    -0.46 0.84
ExerciseAngina*  0.39    -1.85 0.02
Oldpeak          1.02     1.18 0.04
ST_Slope*       -0.38    -0.67 0.02
HeartDisease    -0.21    -1.96 0.02</code></pre>
</div>
</div>
<p>In looking at the summary statistics above, we can see that the minimum value for RestingBP and cholesterol is zero. Using filter(), we can see that 172 of 918 observations have Cholesterol or RestingBP measurements with inappropriate values of zero that could bias the data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>heart_data <span class="sc">|&gt;</span>  <span class="fu">filter</span>(RestingBP <span class="sc">==</span> <span class="dv">0</span> <span class="sc">|</span> Cholesterol <span class="sc">==</span> <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 172 × 12
     Age Sex   ChestPainType RestingBP Cholesterol FastingBS RestingECG MaxHR
   &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;             &lt;dbl&gt;       &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;      &lt;dbl&gt;
 1    65 M     ASY                 115           0         0 Normal        93
 2    32 M     TA                   95           0         1 Normal       127
 3    61 M     ASY                 105           0         1 Normal       110
 4    50 M     ASY                 145           0         1 Normal       139
 5    57 M     ASY                 110           0         1 ST           131
 6    51 M     ASY                 110           0         1 Normal        92
 7    47 M     ASY                 110           0         1 ST           149
 8    60 M     ASY                 160           0         1 Normal       149
 9    55 M     ATA                 140           0         0 ST           150
10    53 M     ASY                 125           0         1 Normal       120
# ℹ 162 more rows
# ℹ 4 more variables: ExerciseAngina &lt;chr&gt;, Oldpeak &lt;dbl&gt;, ST_Slope &lt;chr&gt;,
#   HeartDisease &lt;dbl&gt;</code></pre>
</div>
</div>
<p>A new data set will be created below removing observations for purposes of determining the relationship between the numeric variables in the data and the HeartDisease variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>heart_data_d <span class="ot">&lt;-</span> heart_data <span class="sc">|&gt;</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Cholesterol <span class="sc">!=</span><span class="dv">0</span> <span class="sc">&amp;</span> RestingBP <span class="sc">!=</span> <span class="dv">0</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>heart_data_d</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 746 × 12
     Age Sex   ChestPainType RestingBP Cholesterol FastingBS RestingECG MaxHR
   &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;             &lt;dbl&gt;       &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;      &lt;dbl&gt;
 1    40 M     ATA                 140         289         0 Normal       172
 2    49 F     NAP                 160         180         0 Normal       156
 3    37 M     ATA                 130         283         0 ST            98
 4    48 F     ASY                 138         214         0 Normal       108
 5    54 M     NAP                 150         195         0 Normal       122
 6    39 M     NAP                 120         339         0 Normal       170
 7    45 F     ATA                 130         237         0 Normal       170
 8    54 M     ATA                 110         208         0 Normal       142
 9    37 M     ASY                 140         207         0 Normal       130
10    48 F     ATA                 120         284         0 Normal       120
# ℹ 736 more rows
# ℹ 4 more variables: ExerciseAngina &lt;chr&gt;, Oldpeak &lt;dbl&gt;, ST_Slope &lt;chr&gt;,
#   HeartDisease &lt;dbl&gt;</code></pre>
</div>
</div>
<p>To understand the relationship between the categorical variables and HeartDisease variable, we can look at contingency tables. In looking at the contingency table for Sex and HeartDisease, we can see that a greater proportion of men had heart disease compared to women. This indicates that Sex may be an important predictor for heart disease.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>heart_data <span class="sc">|&gt;</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Sex, HeartDisease) <span class="sc">|&gt;</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>()) <span class="sc">|&gt;</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> HeartDisease, <span class="at">values_from =</span> count)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'Sex'. You can override using the `.groups`
argument.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
# Groups:   Sex [2]
  Sex     `0`   `1`
  &lt;chr&gt; &lt;int&gt; &lt;int&gt;
1 F       143    50
2 M       267   458</code></pre>
</div>
</div>
<p>In looking at ChestPainType, a larger proportion of individuals who had heart disease were categorized as ASY for chest pain (79%), which is the asymptomatic category, compared to other categories.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>heart_data <span class="sc">|&gt;</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(ChestPainType, HeartDisease) <span class="sc">|&gt;</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>(), <span class="at">.groups =</span> <span class="st">"drop"</span>) <span class="sc">|&gt;</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> HeartDisease, <span class="at">values_from =</span> count)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
  ChestPainType   `0`   `1`
  &lt;chr&gt;         &lt;int&gt; &lt;int&gt;
1 ASY             104   392
2 ATA             149    24
3 NAP             131    72
4 TA               26    20</code></pre>
</div>
</div>
<p>For ExerciseAngina, more than 80% of individuals who reported exercise angina had heart disease compared to 25.9% of those with no exercise angina.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>heart_data <span class="sc">|&gt;</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(ExerciseAngina, HeartDisease) <span class="sc">|&gt;</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>(), <span class="at">.groups =</span> <span class="st">"drop"</span>) <span class="sc">|&gt;</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> HeartDisease, <span class="at">values_from =</span> count)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  ExerciseAngina   `0`   `1`
  &lt;chr&gt;          &lt;int&gt; &lt;int&gt;
1 N                355   192
2 Y                 55   316</code></pre>
</div>
</div>
<p>The contingency table for RestingECG and HeartDisease is below. Resting electrocardiogram results ranged from 42-58% for those with heart disease.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>heart_data <span class="sc">|&gt;</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(RestingECG, HeartDisease) <span class="sc">|&gt;</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>(), <span class="at">.groups =</span> <span class="st">"drop"</span>) <span class="sc">|&gt;</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> HeartDisease, <span class="at">values_from =</span> count)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  RestingECG   `0`   `1`
  &lt;chr&gt;      &lt;int&gt; &lt;int&gt;
1 LVH           82   106
2 Normal       267   285
3 ST            61   117</code></pre>
</div>
</div>
<p>For the numeric variables, we can look at correlation of the independent variables with the HeartDisease variable. Correlations were determined using the data with the Cholesterol and RestingBP values of 0 dropped. The correlations shown below indicate that none of the numeric variables has a particularly strong relationship with the HeartDisease variable. The Cholesterol variable has a correlation of 0.104. Given the weak correlation and the number of zeros included for the Cholesterol data, I am going to remove this variable from the data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>vars <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"RestingBP"</span>, <span class="st">"Age"</span>, <span class="st">"Cholesterol"</span>, <span class="st">"MaxHR"</span>, <span class="st">"Oldpeak"</span>)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>corr_values <span class="ot">&lt;-</span> <span class="fu">sapply</span>(heart_data_d[vars], </span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>                      <span class="cf">function</span>(x) <span class="fu">cor</span>(x, heart_data_d<span class="sc">$</span>HeartDisease))</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>corr_values</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  RestingBP         Age Cholesterol       MaxHR     Oldpeak 
  0.1732416   0.2986167   0.1038656  -0.3772122   0.4956963 </code></pre>
</div>
</div>
</section>
<section id="remove-st_slope-variable-and-create-factor-version-of-heartdisease" class="level3">
<h3 class="anchored" data-anchor-id="remove-st_slope-variable-and-create-factor-version-of-heartdisease">2. Remove ST_Slope variable and create factor version of HeartDisease</h3>
<p>As discussed previously, the one errant observation with a 0 recorded for RestingBP will be dropped here. The Cholesterol column is also going to be dropped since it has a low linear correlation with the HeartDisease variable and has 171 zeros recorded. These omissions will be done in this data step of removing the ST_Slope variable and converting HeartDisease to a factor.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>heart_data <span class="ot">&lt;-</span> heart_data <span class="sc">|&gt;</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(RestingBP <span class="sc">!=</span> <span class="dv">0</span>) <span class="sc">|&gt;</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>ST_Slope, <span class="sc">-</span>Cholesterol) <span class="sc">|&gt;</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">HeartDisease =</span> <span class="fu">as.factor</span>(HeartDisease))</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>heart_data</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 917 × 10
     Age Sex   ChestPainType RestingBP FastingBS RestingECG MaxHR ExerciseAngina
   &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;             &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;      &lt;dbl&gt; &lt;chr&gt;         
 1    40 M     ATA                 140         0 Normal       172 N             
 2    49 F     NAP                 160         0 Normal       156 N             
 3    37 M     ATA                 130         0 ST            98 N             
 4    48 F     ASY                 138         0 Normal       108 Y             
 5    54 M     NAP                 150         0 Normal       122 N             
 6    39 M     NAP                 120         0 Normal       170 N             
 7    45 F     ATA                 130         0 Normal       170 N             
 8    54 M     ATA                 110         0 Normal       142 N             
 9    37 M     ASY                 140         0 Normal       130 Y             
10    48 F     ATA                 120         0 Normal       120 N             
# ℹ 907 more rows
# ℹ 2 more variables: Oldpeak &lt;dbl&gt;, HeartDisease &lt;fct&gt;</code></pre>
</div>
</div>
</section>
<section id="create-dummy-columns-for-sex-exerciseangina-chestpaintype-and-restingecg-for-knn-analysis" class="level3">
<h3 class="anchored" data-anchor-id="create-dummy-columns-for-sex-exerciseangina-chestpaintype-and-restingecg-for-knn-analysis">3. Create dummy columns for Sex, ExerciseAngina, ChestPainType and RestingECG for KNN analysis</h3>
<p>To create dummy columns for Sex, ExerciseAngina, ChestPainType and RestingECG, these variables need to be in factor form.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>heart_dataKNN <span class="ot">&lt;-</span> heart_data <span class="sc">|&gt;</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Sex =</span> <span class="fu">as.factor</span>(Sex),</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">ExerciseAngina =</span> <span class="fu">as.factor</span>(ExerciseAngina),</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">ChestPainType =</span> <span class="fu">as.factor</span>(ChestPainType),</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">RestingECG =</span> <span class="fu">as.factor</span>(RestingECG))</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>heart_dataKNN</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 917 × 10
     Age Sex   ChestPainType RestingBP FastingBS RestingECG MaxHR ExerciseAngina
   &lt;dbl&gt; &lt;fct&gt; &lt;fct&gt;             &lt;dbl&gt;     &lt;dbl&gt; &lt;fct&gt;      &lt;dbl&gt; &lt;fct&gt;         
 1    40 M     ATA                 140         0 Normal       172 N             
 2    49 F     NAP                 160         0 Normal       156 N             
 3    37 M     ATA                 130         0 ST            98 N             
 4    48 F     ASY                 138         0 Normal       108 Y             
 5    54 M     NAP                 150         0 Normal       122 N             
 6    39 M     NAP                 120         0 Normal       170 N             
 7    45 F     ATA                 130         0 Normal       170 N             
 8    54 M     ATA                 110         0 Normal       142 N             
 9    37 M     ASY                 140         0 Normal       130 Y             
10    48 F     ATA                 120         0 Normal       120 N             
# ℹ 907 more rows
# ℹ 2 more variables: Oldpeak &lt;dbl&gt;, HeartDisease &lt;fct&gt;</code></pre>
</div>
</div>
<p>The dummyVars() function from the caret package will be used to create our dummy columns. This function adds new columns for each level of the variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>dummy_vars <span class="ot">&lt;-</span> <span class="fu">dummyVars</span>(<span class="sc">~</span> ChestPainType <span class="sc">+</span> RestingECG <span class="sc">+</span> Sex <span class="sc">+</span> ExerciseAngina, </span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>                        <span class="at">data =</span> heart_dataKNN)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="co">#dummy_vars</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>dummies <span class="ot">&lt;-</span> <span class="fu">predict</span>(dummy_vars, <span class="at">newdata =</span> heart_dataKNN)</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a><span class="co">#dummies</span></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>heart_dataKNN <span class="ot">&lt;-</span> heart_dataKNN <span class="sc">|&gt;</span></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>ChestPainType, <span class="sc">-</span>RestingECG, <span class="sc">-</span>Sex, <span class="sc">-</span>ExerciseAngina) <span class="sc">|&gt;</span></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_cols</span>(dummies)</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>heart_dataKNN</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 917 × 17
     Age RestingBP FastingBS MaxHR Oldpeak HeartDisease ChestPainType.ASY
   &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;fct&gt;                    &lt;dbl&gt;
 1    40       140         0   172     0   0                            0
 2    49       160         0   156     1   1                            0
 3    37       130         0    98     0   0                            0
 4    48       138         0   108     1.5 1                            1
 5    54       150         0   122     0   0                            0
 6    39       120         0   170     0   0                            0
 7    45       130         0   170     0   0                            0
 8    54       110         0   142     0   0                            0
 9    37       140         0   130     1.5 1                            1
10    48       120         0   120     0   0                            0
# ℹ 907 more rows
# ℹ 10 more variables: ChestPainType.ATA &lt;dbl&gt;, ChestPainType.NAP &lt;dbl&gt;,
#   ChestPainType.TA &lt;dbl&gt;, RestingECG.LVH &lt;dbl&gt;, RestingECG.Normal &lt;dbl&gt;,
#   RestingECG.ST &lt;dbl&gt;, Sex.F &lt;dbl&gt;, Sex.M &lt;dbl&gt;, ExerciseAngina.N &lt;dbl&gt;,
#   ExerciseAngina.Y &lt;dbl&gt;</code></pre>
</div>
</div>
</section>
</section>
<section id="split-the-data" class="level2">
<h2 class="anchored" data-anchor-id="split-the-data">Split the data</h2>
<p>Now that the data has been manipulated as necessary, we want to split it into training and test sets. This can be done using createDataPartition() from the caret package. The training set will be set to include 80% of the data and the test set 20%.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">100</span>)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>trainIndex <span class="ot">&lt;-</span> <span class="fu">createDataPartition</span>(heart_dataKNN<span class="sc">$</span>HeartDisease, </span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">p =</span> <span class="fl">0.8</span>, </span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">list =</span> <span class="cn">FALSE</span>)</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>heartTrain <span class="ot">&lt;-</span> heart_dataKNN[trainIndex, ]</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>heartTest <span class="ot">&lt;-</span> heart_dataKNN[<span class="sc">-</span>trainIndex, ]</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a><span class="co">#heartTrain</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a><span class="co">#heartTest</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="knn" class="level2">
<h2 class="anchored" data-anchor-id="knn">KNN</h2>
<p>Before KNN can be performed, the test and train sets should be pre-processed by centering and scaling. This is done using preProcess() from caret and specifying center and scale in the method.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>preProcValues <span class="ot">&lt;-</span> <span class="fu">preProcess</span>(heartTrain, <span class="at">method =</span> <span class="fu">c</span>(<span class="st">"center"</span>, <span class="st">"scale"</span>))</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>heartTrainTransformed <span class="ot">&lt;-</span> <span class="fu">predict</span>(preProcValues, heartTrain)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>heartTestTransformed <span class="ot">&lt;-</span> <span class="fu">predict</span>(preProcValues, heartTest)</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>heartTrainTransformed</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 734 × 17
       Age RestingBP FastingBS  MaxHR Oldpeak HeartDisease ChestPainType.ASY
     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt; &lt;fct&gt;                    &lt;dbl&gt;
 1 -1.48       0.427    -0.538  1.37  -0.844  0                       -1.09 
 2 -0.505      1.55     -0.538  0.743  0.0723 1                       -1.09 
 3 -1.80      -0.133    -0.538 -1.53  -0.844  0                       -1.09 
 4 -0.613      0.315    -0.538 -1.13   0.530  1                        0.918
 5  0.0344     0.987    -0.538 -0.587 -0.844  0                       -1.09 
 6 -1.58      -0.692    -0.538  1.29  -0.844  0                       -1.09 
 7 -0.937     -0.133    -0.538  1.29  -0.844  0                       -1.09 
 8  0.0344    -1.25     -0.538  0.196 -0.844  0                       -1.09 
 9 -0.613     -0.692    -0.538 -0.665 -0.844  0                       -1.09 
10  0.466      0.203    -0.538 -1.49   0.988  1                       -1.09 
# ℹ 724 more rows
# ℹ 10 more variables: ChestPainType.ATA &lt;dbl&gt;, ChestPainType.NAP &lt;dbl&gt;,
#   ChestPainType.TA &lt;dbl&gt;, RestingECG.LVH &lt;dbl&gt;, RestingECG.Normal &lt;dbl&gt;,
#   RestingECG.ST &lt;dbl&gt;, Sex.F &lt;dbl&gt;, Sex.M &lt;dbl&gt;, ExerciseAngina.N &lt;dbl&gt;,
#   ExerciseAngina.Y &lt;dbl&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>heartTestTransformed</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 183 × 17
      Age RestingBP FastingBS     MaxHR Oldpeak HeartDisease ChestPainType.ASY
    &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;fct&gt;                    &lt;dbl&gt;
 1 -1.80      0.427    -0.538 -0.274     0.530  1                        0.918
 2 -1.80     -0.133    -0.538  0.196    -0.844  0                       -1.09 
 3 -1.58     -0.692    -0.538  0.313    -0.844  0                       -1.09 
 4 -0.505     0.427    -0.538  0.117     0.0723 1                        0.918
 5 -1.26     -0.972    -0.538  0.000107 -0.844  0                       -1.09 
 6 -1.91     -0.692    -0.538  0.900     1.90   1                       -1.09 
 7  0.250    -0.133    -0.538 -0.900    -0.844  0                       -1.09 
 8 -1.37     -0.133    -0.538 -0.274     0.988  1                        0.918
 9 -2.34     -0.413    -0.538  0.704    -0.844  0                       -1.09 
10 -0.613     0.987    -0.538 -0.274     0.0723 0                        0.918
# ℹ 173 more rows
# ℹ 10 more variables: ChestPainType.ATA &lt;dbl&gt;, ChestPainType.NAP &lt;dbl&gt;,
#   ChestPainType.TA &lt;dbl&gt;, RestingECG.LVH &lt;dbl&gt;, RestingECG.Normal &lt;dbl&gt;,
#   RestingECG.ST &lt;dbl&gt;, Sex.F &lt;dbl&gt;, Sex.M &lt;dbl&gt;, ExerciseAngina.N &lt;dbl&gt;,
#   ExerciseAngina.Y &lt;dbl&gt;</code></pre>
</div>
</div>
<p>Now that the data is standardized, we can proceed with the KNN analysis. Since we want to use cross validation with repeats, we use the method repeatedcv. The number option is for the number of cross validation folds, which is input as 10. Lastly, we want to set the number of repeats, which is set at 3. For the KNN fit, we need to specify the tuneGrid, which for KNN are the options for k, put in a data frame. A k of 1-40 was selected.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>heartTrainControl <span class="ot">&lt;-</span> <span class="fu">trainControl</span>(<span class="at">method =</span> <span class="st">"repeatedcv"</span>, <span class="at">number =</span> <span class="dv">10</span>, </span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">repeats =</span> <span class="dv">3</span>)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">100</span>)</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>knnFit <span class="ot">&lt;-</span> <span class="fu">train</span>(HeartDisease <span class="sc">~</span> ., <span class="at">data =</span> heartTrainTransformed, <span class="at">method =</span> <span class="st">"knn"</span>,</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">trControl =</span> heartTrainControl, <span class="at">tuneGrid =</span> <span class="fu">data.frame</span>(<span class="at">k =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">40</span>))</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>knnFit<span class="sc">$</span>results</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    k  Accuracy     Kappa AccuracySD    KappaSD
1   1 0.7560348 0.5083305 0.03908606 0.07858178
2   2 0.7505619 0.4973646 0.04315820 0.08667276
3   3 0.8078123 0.6125007 0.03449592 0.06915577
4   4 0.7987224 0.5949910 0.03732584 0.07302272
5   5 0.8178403 0.6326833 0.03146719 0.06329092
6   6 0.8192165 0.6353406 0.03328072 0.06701394
7   7 0.8164827 0.6302383 0.03442645 0.06896029
8   8 0.8192288 0.6357303 0.03920394 0.07795160
9   9 0.8241646 0.6457463 0.04053573 0.08079609
10 10 0.8210179 0.6398867 0.04150722 0.08236451
11 11 0.8205738 0.6389432 0.04054994 0.08089258
12 12 0.8173461 0.6318732 0.03823004 0.07706092
13 13 0.8187225 0.6348866 0.03459070 0.06950247
14 14 0.8133049 0.6237867 0.03671087 0.07425393
15 15 0.8123728 0.6221175 0.03251453 0.06588079
16 16 0.8110401 0.6191948 0.03380803 0.06908881
17 17 0.8169581 0.6309383 0.03544762 0.07203786
18 18 0.8179147 0.6328339 0.03616942 0.07318882
19 19 0.8215181 0.6401511 0.03503157 0.07039590
20 20 0.8165261 0.6296579 0.03472284 0.07020461
21 21 0.8183031 0.6331068 0.03259754 0.06676725
22 22 0.8201295 0.6369344 0.03679740 0.07500759
23 23 0.8183091 0.6329798 0.03593383 0.07311414
24 24 0.8155570 0.6275439 0.03509479 0.07159433
25 25 0.8155757 0.6274689 0.03826847 0.07773644
26 26 0.8132926 0.6225859 0.03895400 0.07986157
27 27 0.8164764 0.6287413 0.03837586 0.07857522
28 28 0.8196794 0.6357497 0.03804745 0.07764006
29 29 0.8223943 0.6408510 0.03878969 0.07948103
30 30 0.8210370 0.6381958 0.03879300 0.07928379
31 31 0.8182724 0.6322676 0.03990398 0.08185034
32 32 0.8178219 0.6310872 0.04212248 0.08600873
33 33 0.8169025 0.6289354 0.04108072 0.08463479
34 34 0.8155572 0.6259794 0.03859579 0.07975261
35 35 0.8150570 0.6249479 0.04278291 0.08830123
36 36 0.8159953 0.6267008 0.04229388 0.08773405
37 37 0.8164829 0.6272087 0.03878179 0.08115201
38 38 0.8178403 0.6299563 0.04204495 0.08734774
39 39 0.8169209 0.6276161 0.04306894 0.08992802
40 40 0.8187227 0.6314024 0.04304583 0.08949362</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>knnFit<span class="sc">$</span>bestTune</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  k
9 9</code></pre>
</div>
</div>
<p>The best tune was for k=9, with an accuracy of 82.42 %. Next, we can check how well the model performs on our test set by obtaining a confusion matrix using confusionMatrix(). Looking at the output below, the prediction accuracy on our test set is 81.97%, which isn’t that different from the training accuracy of 82.66%. Note that when KNN was performed with the Cholesterol variable (zeros dropped), the accuracy on the trained data was 82.66% and the accuracy on the test set was 80.87%.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confusionMatrix</span>(<span class="at">data =</span> heartTestTransformed<span class="sc">$</span>HeartDisease, </span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">reference =</span> <span class="fu">predict</span>(knnFit, <span class="at">newdata =</span> heartTestTransformed))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction  0  1
         0 64 18
         1 15 86
                                          
               Accuracy : 0.8197          
                 95% CI : (0.7562, 0.8725)
    No Information Rate : 0.5683          
    P-Value [Acc &gt; NIR] : 4.793e-13       
                                          
                  Kappa : 0.6342          
                                          
 Mcnemar's Test P-Value : 0.7277          
                                          
            Sensitivity : 0.8101          
            Specificity : 0.8269          
         Pos Pred Value : 0.7805          
         Neg Pred Value : 0.8515          
             Prevalence : 0.4317          
         Detection Rate : 0.3497          
   Detection Prevalence : 0.4481          
      Balanced Accuracy : 0.8185          
                                          
       'Positive' Class : 0               
                                          </code></pre>
</div>
</div>
</section>
<section id="logistic-regression" class="level2">
<h2 class="anchored" data-anchor-id="logistic-regression">Logistic Regression</h2>
<p>For logistic regression classification, I’d suggest the following 3 models.</p>
<ol type="1">
<li>Full data set minus cholesterol variable for reasons stated previously</li>
<li>Full data set minus Cholesterol and RestingBP since they have the lowest correlations with HeartDisease</li>
<li>Full data set minus Cholesterol, RestingBP and Resting ECG. RestingECG will be removed since the differences in RestingECG for those with and without heart disease don’t appear drastically different based on the contingency table. Obviously correlation data would be more accurate to look at to determine the validity of dropping this variable.</li>
</ol>
<p>For the first model, we can use the heart_data created in the Quick EDQ/Data Preparation section. This data set maintains the original categorical variables before adding dummy columns for KNN analysis. New training and test sets are created below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">100</span>)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>trainIndex <span class="ot">&lt;-</span> <span class="fu">createDataPartition</span>(heart_data<span class="sc">$</span>HeartDisease, </span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">p =</span> <span class="fl">0.8</span>, </span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">list =</span> <span class="cn">FALSE</span>)</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>heartTrain <span class="ot">&lt;-</span> heart_data[trainIndex, ]</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>heartTest <span class="ot">&lt;-</span> heart_data[<span class="sc">-</span>trainIndex, ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next, the data will be centered and scaled.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>preProcValues <span class="ot">&lt;-</span> <span class="fu">preProcess</span>(heartTrain, <span class="at">method =</span> <span class="fu">c</span>(<span class="st">"center"</span>, <span class="st">"scale"</span>))</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>heartTrainTransformed <span class="ot">&lt;-</span> <span class="fu">predict</span>(preProcValues, heartTrain)</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>heartTestTransformed <span class="ot">&lt;-</span> <span class="fu">predict</span>(preProcValues, heartTest)</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>heartTrainTransformed</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 734 × 10
       Age Sex   ChestPainType RestingBP FastingBS RestingECG  MaxHR
     &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;             &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;       &lt;dbl&gt;
 1 -1.48   M     ATA               0.427    -0.538 Normal      1.37 
 2 -0.505  F     NAP               1.55     -0.538 Normal      0.743
 3 -1.80   M     ATA              -0.133    -0.538 ST         -1.53 
 4 -0.613  F     ASY               0.315    -0.538 Normal     -1.13 
 5  0.0344 M     NAP               0.987    -0.538 Normal     -0.587
 6 -1.58   M     NAP              -0.692    -0.538 Normal      1.29 
 7 -0.937  F     ATA              -0.133    -0.538 Normal      1.29 
 8  0.0344 M     ATA              -1.25     -0.538 Normal      0.196
 9 -0.613  F     ATA              -0.692    -0.538 Normal     -0.665
10  0.466  M     ATA               0.203    -0.538 ST         -1.49 
# ℹ 724 more rows
# ℹ 3 more variables: ExerciseAngina &lt;chr&gt;, Oldpeak &lt;dbl&gt;, HeartDisease &lt;fct&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>heartTestTransformed</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 183 × 10
      Age Sex   ChestPainType RestingBP FastingBS RestingECG     MaxHR
    &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;             &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;          &lt;dbl&gt;
 1 -1.80  M     ASY               0.427    -0.538 Normal     -0.274   
 2 -1.80  F     NAP              -0.133    -0.538 Normal      0.196   
 3 -1.58  M     ATA              -0.692    -0.538 Normal      0.313   
 4 -0.505 M     ASY               0.427    -0.538 Normal      0.117   
 5 -1.26  F     NAP              -0.972    -0.538 ST          0.000107
 6 -1.91  M     ATA              -0.692    -0.538 Normal      0.900   
 7  0.250 M     NAP              -0.133    -0.538 Normal     -0.900   
 8 -1.37  M     ASY              -0.133    -0.538 ST         -0.274   
 9 -2.34  M     ATA              -0.413    -0.538 Normal      0.704   
10 -0.613 F     ASY               0.987    -0.538 Normal     -0.274   
# ℹ 173 more rows
# ℹ 3 more variables: ExerciseAngina &lt;chr&gt;, Oldpeak &lt;dbl&gt;, HeartDisease &lt;fct&gt;</code></pre>
</div>
</div>
<p>Finally, the model will be run using the caret package, with the same specifications as for KNN, with the exception of a tuning parameter. Here, we use the method “glm” and specify “binomial” for family since we have a binary response for heart disease.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>heartTrainControl1 <span class="ot">&lt;-</span> <span class="fu">trainControl</span>(<span class="at">method =</span> <span class="st">"repeatedcv"</span>, <span class="at">number =</span> <span class="dv">10</span>, </span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">repeats =</span> <span class="dv">3</span>)</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">100</span>)</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>glmFit1 <span class="ot">&lt;-</span> <span class="fu">train</span>(HeartDisease <span class="sc">~</span> ., <span class="at">data =</span> heartTrainTransformed, <span class="at">method =</span> <span class="st">"glm"</span>,</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">trControl =</span> heartTrainControl1, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>glmFit1<span class="sc">$</span>results</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  parameter Accuracy     Kappa AccuracySD   KappaSD
1      none 0.814237 0.6233833 0.04835864 0.0989383</code></pre>
</div>
</div>
<p>The first model has a prediction accuracy of 81.42%. For the second model, RestingBP will be dropped from the transformed data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>heartTrainTransformed2 <span class="ot">&lt;-</span> heartTrainTransformed <span class="sc">|&gt;</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>RestingBP)</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>heartTestTransformed2 <span class="ot">&lt;-</span> heartTestTransformed <span class="sc">|&gt;</span></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>RestingBP)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now the model 2 can be fit as seen below. In looking at the fit results, we can see that dropping the RestingBP variable did not improve the accuracy, which now sits slightly lower at 81.38%</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>heartTrainControl2 <span class="ot">&lt;-</span> <span class="fu">trainControl</span>(<span class="at">method =</span> <span class="st">"repeatedcv"</span>, <span class="at">number =</span> <span class="dv">10</span>, </span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">repeats =</span> <span class="dv">3</span>)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">100</span>)</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>glmFit2 <span class="ot">&lt;-</span> <span class="fu">train</span>(HeartDisease <span class="sc">~</span> ., <span class="at">data =</span> heartTrainTransformed2, <span class="at">method =</span> <span class="st">"glm"</span>,</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">trControl =</span> heartTrainControl2, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>glmFit2<span class="sc">$</span>results</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  parameter  Accuracy     Kappa AccuracySD   KappaSD
1      none 0.8137552 0.6227338 0.04991677 0.1016742</code></pre>
</div>
</div>
<p>For model 3, the RestingECG variable was removed from the transformed train and test sets and the model rerun. This model has an accuracy of 81.15%, which is lower than the previous two models.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>heartTrainTransformed3 <span class="ot">&lt;-</span> heartTrainTransformed2 <span class="sc">|&gt;</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>RestingECG)</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>heartTestTransformed3 <span class="ot">&lt;-</span> heartTestTransformed2 <span class="sc">|&gt;</span></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>RestingECG)</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>heartTrainControl3 <span class="ot">&lt;-</span> <span class="fu">trainControl</span>(<span class="at">method =</span> <span class="st">"repeatedcv"</span>, <span class="at">number =</span> <span class="dv">10</span>, </span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">repeats =</span> <span class="dv">3</span>)</span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">100</span>)</span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>glmFit3 <span class="ot">&lt;-</span> <span class="fu">train</span>(HeartDisease <span class="sc">~</span> ., <span class="at">data =</span> heartTrainTransformed3, <span class="at">method =</span> <span class="st">"glm"</span>,</span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a>                <span class="at">trControl =</span> heartTrainControl3, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a>glmFit3<span class="sc">$</span>results</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  parameter  Accuracy     Kappa AccuracySD   KappaSD
1      none 0.8114719 0.6179063 0.05034342 0.1026898</code></pre>
</div>
</div>
<p>Out of all 3 models, the first one with the Cholesterol variable removed is the most accurate, with an accuracy rate of 81.42%. Accuracy on the test set is shown below using confusionMatrix(). The accuracy on the test data set is 81.97%. Interestingly, this exactly the same as the accuracy for the KNN model presented previously.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confusionMatrix</span>(<span class="at">data =</span> heartTestTransformed<span class="sc">$</span>HeartDisease, </span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">reference =</span> <span class="fu">predict</span>(glmFit1, <span class="at">newdata =</span> heartTestTransformed))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction  0  1
         0 65 17
         1 16 85
                                          
               Accuracy : 0.8197          
                 95% CI : (0.7562, 0.8725)
    No Information Rate : 0.5574          
    P-Value [Acc &gt; NIR] : 5.843e-14       
                                          
                  Kappa : 0.635           
                                          
 Mcnemar's Test P-Value : 1               
                                          
            Sensitivity : 0.8025          
            Specificity : 0.8333          
         Pos Pred Value : 0.7927          
         Neg Pred Value : 0.8416          
             Prevalence : 0.4426          
         Detection Rate : 0.3552          
   Detection Prevalence : 0.4481          
      Balanced Accuracy : 0.8179          
                                          
       'Positive' Class : 0               
                                          </code></pre>
</div>
</div>
</section>
<section id="tree-models" class="level2">
<h2 class="anchored" data-anchor-id="tree-models">Tree Models</h2>
<p>Now, we want to fit the data from the 3 posited models in the logistic regression section to various types of tree models. Since the same 3 models used in logistic regression will be used here, the same training and test sets from the logistic regression section will be used here.</p>
<section id="classification-tree" class="level3">
<h3 class="anchored" data-anchor-id="classification-tree">Classification Tree</h3>
<p>The code and output for model 1 where the Cholesterol variable is removed is presented below. Since this is model 1, we will use heartTrainControl1 from the logistic regression section, which used repeatedcv, 10 folds and 3 repeats. The best model for model 1 is the one with a complexity parameter of 0.004, with an accuracy of 79.65%.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">100</span>)</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>treeFit1 <span class="ot">&lt;-</span> <span class="fu">train</span>(HeartDisease <span class="sc">~</span> ., <span class="at">data =</span> heartTrainTransformed, </span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">method =</span> <span class="st">"rpart"</span>,</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">trControl =</span> heartTrainControl1, </span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">tuneGrid =</span> <span class="fu">expand.grid</span>(<span class="at">cp =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="fl">0.1</span>, <span class="fl">0.001</span>)))</span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>treeFit1<span class="sc">$</span>results</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       cp  Accuracy     Kappa AccuracySD    KappaSD
1   0.000 0.7869805 0.5674633 0.04593100 0.09380032
2   0.001 0.7923859 0.5778321 0.04644381 0.09482932
3   0.002 0.7923859 0.5773961 0.04644381 0.09500933
4   0.003 0.7932930 0.5790846 0.04678119 0.09567766
5   0.004 0.7960515 0.5840635 0.04706789 0.09668206
6   0.005 0.7942250 0.5805555 0.04653982 0.09562957
7   0.006 0.7924107 0.5774316 0.04712529 0.09635247
8   0.007 0.7819945 0.5564815 0.04608977 0.09369019
9   0.008 0.7824575 0.5578582 0.04708382 0.09507559
10  0.009 0.7838088 0.5605707 0.04690218 0.09510793
11  0.010 0.7833522 0.5604414 0.04421452 0.08913738
12  0.011 0.7887761 0.5711604 0.04046531 0.08087986
13  0.012 0.7896708 0.5733335 0.03970507 0.07962357
14  0.013 0.7896708 0.5736162 0.03970507 0.07974504
15  0.014 0.7933053 0.5812763 0.04105578 0.08218375
16  0.015 0.7946752 0.5844556 0.04130972 0.08269487
17  0.016 0.7946752 0.5844556 0.04130972 0.08269487
18  0.017 0.7946752 0.5844556 0.04130972 0.08269487
19  0.018 0.7946752 0.5844556 0.04130972 0.08269487
20  0.019 0.7946752 0.5844556 0.04130972 0.08269487
21  0.020 0.7946752 0.5844556 0.04130972 0.08269487
22  0.021 0.7932863 0.5818885 0.04257838 0.08514344
23  0.022 0.7932863 0.5818885 0.04257838 0.08514344
24  0.023 0.7923854 0.5802959 0.04248062 0.08504177
25  0.024 0.7919287 0.5794062 0.04237805 0.08485087
26  0.025 0.7919287 0.5794062 0.04237805 0.08485087
27  0.026 0.7919287 0.5794062 0.04237805 0.08485087
28  0.027 0.7919287 0.5794062 0.04237805 0.08485087
29  0.028 0.7923854 0.5804104 0.04323552 0.08671784
30  0.029 0.7923854 0.5804104 0.04323552 0.08671784
31  0.030 0.7923854 0.5804104 0.04323552 0.08671784
32  0.031 0.7923854 0.5804104 0.04323552 0.08671784
33  0.032 0.7923854 0.5804104 0.04323552 0.08671784
34  0.033 0.7923854 0.5804104 0.04323552 0.08671784
35  0.034 0.7896642 0.5753069 0.04595731 0.09170107
36  0.035 0.7896642 0.5753069 0.04595731 0.09170107
37  0.036 0.7896642 0.5753069 0.04595731 0.09170107
38  0.037 0.7896642 0.5753069 0.04595731 0.09170107
39  0.038 0.7860359 0.5686670 0.04880446 0.09701877
40  0.039 0.7860359 0.5686670 0.04880446 0.09701877
41  0.040 0.7860359 0.5686670 0.04880446 0.09701877
42  0.041 0.7824012 0.5622764 0.04688279 0.09331750
43  0.042 0.7824012 0.5622764 0.04688279 0.09331750
44  0.043 0.7824012 0.5622764 0.04688279 0.09331750
45  0.044 0.7824012 0.5622764 0.04688279 0.09331750
46  0.045 0.7824012 0.5624403 0.04688279 0.09331462
47  0.046 0.7824012 0.5624403 0.04688279 0.09331462
48  0.047 0.7824012 0.5624403 0.04688279 0.09331462
49  0.048 0.7846597 0.5675788 0.04801399 0.09579789
50  0.049 0.7846597 0.5675788 0.04801399 0.09579789
51  0.050 0.7846597 0.5675788 0.04801399 0.09579789
52  0.051 0.7846597 0.5675788 0.04801399 0.09579789
53  0.052 0.7846597 0.5675788 0.04801399 0.09579789
54  0.053 0.7846597 0.5675788 0.04801399 0.09579789
55  0.054 0.7846597 0.5675788 0.04801399 0.09579789
56  0.055 0.7846597 0.5675788 0.04801399 0.09579789
57  0.056 0.7846597 0.5675788 0.04801399 0.09579789
58  0.057 0.7846597 0.5675788 0.04801399 0.09579789
59  0.058 0.7846597 0.5675788 0.04801399 0.09579789
60  0.059 0.7846597 0.5675788 0.04801399 0.09579789
61  0.060 0.7846597 0.5675788 0.04801399 0.09579789
62  0.061 0.7846597 0.5675788 0.04801399 0.09579789
63  0.062 0.7846597 0.5675788 0.04801399 0.09579789
64  0.063 0.7846597 0.5675788 0.04801399 0.09579789
65  0.064 0.7846597 0.5675788 0.04801399 0.09579789
66  0.065 0.7846597 0.5675788 0.04801399 0.09579789
67  0.066 0.7846597 0.5675788 0.04801399 0.09579789
68  0.067 0.7846597 0.5675788 0.04801399 0.09579789
69  0.068 0.7846597 0.5675788 0.04801399 0.09579789
70  0.069 0.7846597 0.5675788 0.04801399 0.09579789
71  0.070 0.7846597 0.5675788 0.04801399 0.09579789
72  0.071 0.7846597 0.5675788 0.04801399 0.09579789
73  0.072 0.7846597 0.5675788 0.04801399 0.09579789
74  0.073 0.7846597 0.5675788 0.04801399 0.09579789
75  0.074 0.7846597 0.5675788 0.04801399 0.09579789
76  0.075 0.7846597 0.5675788 0.04801399 0.09579789
77  0.076 0.7846597 0.5675788 0.04801399 0.09579789
78  0.077 0.7846597 0.5675788 0.04801399 0.09579789
79  0.078 0.7846597 0.5675788 0.04801399 0.09579789
80  0.079 0.7846597 0.5675788 0.04801399 0.09579789
81  0.080 0.7846597 0.5675788 0.04801399 0.09579789
82  0.081 0.7846597 0.5675788 0.04801399 0.09579789
83  0.082 0.7846597 0.5675788 0.04801399 0.09579789
84  0.083 0.7846597 0.5675788 0.04801399 0.09579789
85  0.084 0.7846597 0.5675788 0.04801399 0.09579789
86  0.085 0.7846597 0.5675788 0.04801399 0.09579789
87  0.086 0.7846597 0.5675788 0.04801399 0.09579789
88  0.087 0.7846597 0.5675788 0.04801399 0.09579789
89  0.088 0.7846597 0.5675788 0.04801399 0.09579789
90  0.089 0.7846597 0.5675788 0.04801399 0.09579789
91  0.090 0.7846597 0.5675788 0.04801399 0.09579789
92  0.091 0.7846597 0.5675788 0.04801399 0.09579789
93  0.092 0.7846597 0.5675788 0.04801399 0.09579789
94  0.093 0.7846597 0.5675788 0.04801399 0.09579789
95  0.094 0.7846597 0.5675788 0.04801399 0.09579789
96  0.095 0.7846597 0.5675788 0.04801399 0.09579789
97  0.096 0.7846597 0.5675788 0.04801399 0.09579789
98  0.097 0.7846597 0.5675788 0.04801399 0.09579789
99  0.098 0.7846597 0.5675788 0.04801399 0.09579789
100 0.099 0.7846597 0.5675788 0.04801399 0.09579789
101 0.100 0.7846597 0.5675788 0.04801399 0.09579789</code></pre>
</div>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>treeFit1<span class="sc">$</span>bestTune</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     cp
5 0.004</code></pre>
</div>
</div>
<p>Now the same steps will be performed for model 2. The best model here is the one with a cp of 0.003m which has an accuracy of 80.20%.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">100</span>)</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>treeFit2 <span class="ot">&lt;-</span> <span class="fu">train</span>(HeartDisease <span class="sc">~</span> ., <span class="at">data =</span> heartTrainTransformed2, </span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">method =</span> <span class="st">"rpart"</span>,</span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">trControl =</span> heartTrainControl, </span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">tuneGrid =</span> <span class="fu">expand.grid</span>(<span class="at">cp =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="fl">0.1</span>, <span class="fl">0.001</span>)))</span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a>treeFit2<span class="sc">$</span>results</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       cp  Accuracy     Kappa AccuracySD    KappaSD
1   0.000 0.7974217 0.5870229 0.04278024 0.08798146
2   0.001 0.7974217 0.5870229 0.04278024 0.08798146
3   0.002 0.8015066 0.5949823 0.04187390 0.08613788
4   0.003 0.8019571 0.5958583 0.04174917 0.08590160
5   0.004 0.7960579 0.5838254 0.04261605 0.08745106
6   0.005 0.7915287 0.5752893 0.04263313 0.08661325
7   0.006 0.7856230 0.5638542 0.04633216 0.09408682
8   0.007 0.7770087 0.5462400 0.04435446 0.09011417
9   0.008 0.7770150 0.5465962 0.04387992 0.08877674
10  0.009 0.7801744 0.5531536 0.04357382 0.08858365
11  0.010 0.7824389 0.5583837 0.04107395 0.08307212
12  0.011 0.7892327 0.5721716 0.04092684 0.08165643
13  0.012 0.7887576 0.5712730 0.03957862 0.07964703
14  0.013 0.7896708 0.5736162 0.03970507 0.07974504
15  0.014 0.7933053 0.5812763 0.04105578 0.08218375
16  0.015 0.7946752 0.5844556 0.04130972 0.08269487
17  0.016 0.7946752 0.5844556 0.04130972 0.08269487
18  0.017 0.7946752 0.5844556 0.04130972 0.08269487
19  0.018 0.7946752 0.5844556 0.04130972 0.08269487
20  0.019 0.7946752 0.5844556 0.04130972 0.08269487
21  0.020 0.7946752 0.5844556 0.04130972 0.08269487
22  0.021 0.7932863 0.5818885 0.04257838 0.08514344
23  0.022 0.7932863 0.5818885 0.04257838 0.08514344
24  0.023 0.7923854 0.5802959 0.04248062 0.08504177
25  0.024 0.7919287 0.5794062 0.04237805 0.08485087
26  0.025 0.7919287 0.5794062 0.04237805 0.08485087
27  0.026 0.7919287 0.5794062 0.04237805 0.08485087
28  0.027 0.7919287 0.5794062 0.04237805 0.08485087
29  0.028 0.7923854 0.5804104 0.04323552 0.08671784
30  0.029 0.7923854 0.5804104 0.04323552 0.08671784
31  0.030 0.7923854 0.5804104 0.04323552 0.08671784
32  0.031 0.7923854 0.5804104 0.04323552 0.08671784
33  0.032 0.7923854 0.5804104 0.04323552 0.08671784
34  0.033 0.7923854 0.5804104 0.04323552 0.08671784
35  0.034 0.7896642 0.5753069 0.04595731 0.09170107
36  0.035 0.7896642 0.5753069 0.04595731 0.09170107
37  0.036 0.7896642 0.5753069 0.04595731 0.09170107
38  0.037 0.7896642 0.5753069 0.04595731 0.09170107
39  0.038 0.7860359 0.5686670 0.04880446 0.09701877
40  0.039 0.7860359 0.5686670 0.04880446 0.09701877
41  0.040 0.7860359 0.5686670 0.04880446 0.09701877
42  0.041 0.7824012 0.5622764 0.04688279 0.09331750
43  0.042 0.7824012 0.5622764 0.04688279 0.09331750
44  0.043 0.7824012 0.5622764 0.04688279 0.09331750
45  0.044 0.7824012 0.5622764 0.04688279 0.09331750
46  0.045 0.7824012 0.5624403 0.04688279 0.09331462
47  0.046 0.7824012 0.5624403 0.04688279 0.09331462
48  0.047 0.7824012 0.5624403 0.04688279 0.09331462
49  0.048 0.7846597 0.5675788 0.04801399 0.09579789
50  0.049 0.7846597 0.5675788 0.04801399 0.09579789
51  0.050 0.7846597 0.5675788 0.04801399 0.09579789
52  0.051 0.7846597 0.5675788 0.04801399 0.09579789
53  0.052 0.7846597 0.5675788 0.04801399 0.09579789
54  0.053 0.7846597 0.5675788 0.04801399 0.09579789
55  0.054 0.7846597 0.5675788 0.04801399 0.09579789
56  0.055 0.7846597 0.5675788 0.04801399 0.09579789
57  0.056 0.7846597 0.5675788 0.04801399 0.09579789
58  0.057 0.7846597 0.5675788 0.04801399 0.09579789
59  0.058 0.7846597 0.5675788 0.04801399 0.09579789
60  0.059 0.7846597 0.5675788 0.04801399 0.09579789
61  0.060 0.7846597 0.5675788 0.04801399 0.09579789
62  0.061 0.7846597 0.5675788 0.04801399 0.09579789
63  0.062 0.7846597 0.5675788 0.04801399 0.09579789
64  0.063 0.7846597 0.5675788 0.04801399 0.09579789
65  0.064 0.7846597 0.5675788 0.04801399 0.09579789
66  0.065 0.7846597 0.5675788 0.04801399 0.09579789
67  0.066 0.7846597 0.5675788 0.04801399 0.09579789
68  0.067 0.7846597 0.5675788 0.04801399 0.09579789
69  0.068 0.7846597 0.5675788 0.04801399 0.09579789
70  0.069 0.7846597 0.5675788 0.04801399 0.09579789
71  0.070 0.7846597 0.5675788 0.04801399 0.09579789
72  0.071 0.7846597 0.5675788 0.04801399 0.09579789
73  0.072 0.7846597 0.5675788 0.04801399 0.09579789
74  0.073 0.7846597 0.5675788 0.04801399 0.09579789
75  0.074 0.7846597 0.5675788 0.04801399 0.09579789
76  0.075 0.7846597 0.5675788 0.04801399 0.09579789
77  0.076 0.7846597 0.5675788 0.04801399 0.09579789
78  0.077 0.7846597 0.5675788 0.04801399 0.09579789
79  0.078 0.7846597 0.5675788 0.04801399 0.09579789
80  0.079 0.7846597 0.5675788 0.04801399 0.09579789
81  0.080 0.7846597 0.5675788 0.04801399 0.09579789
82  0.081 0.7846597 0.5675788 0.04801399 0.09579789
83  0.082 0.7846597 0.5675788 0.04801399 0.09579789
84  0.083 0.7846597 0.5675788 0.04801399 0.09579789
85  0.084 0.7846597 0.5675788 0.04801399 0.09579789
86  0.085 0.7846597 0.5675788 0.04801399 0.09579789
87  0.086 0.7846597 0.5675788 0.04801399 0.09579789
88  0.087 0.7846597 0.5675788 0.04801399 0.09579789
89  0.088 0.7846597 0.5675788 0.04801399 0.09579789
90  0.089 0.7846597 0.5675788 0.04801399 0.09579789
91  0.090 0.7846597 0.5675788 0.04801399 0.09579789
92  0.091 0.7846597 0.5675788 0.04801399 0.09579789
93  0.092 0.7846597 0.5675788 0.04801399 0.09579789
94  0.093 0.7846597 0.5675788 0.04801399 0.09579789
95  0.094 0.7846597 0.5675788 0.04801399 0.09579789
96  0.095 0.7846597 0.5675788 0.04801399 0.09579789
97  0.096 0.7846597 0.5675788 0.04801399 0.09579789
98  0.097 0.7846597 0.5675788 0.04801399 0.09579789
99  0.098 0.7846597 0.5675788 0.04801399 0.09579789
100 0.099 0.7846597 0.5675788 0.04801399 0.09579789
101 0.100 0.7846597 0.5675788 0.04801399 0.09579789</code></pre>
</div>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>treeFit2<span class="sc">$</span>bestTune</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     cp
4 0.003</code></pre>
</div>
</div>
<p>Next is model 3, which excludes Cholesterol, RestingBP and RestingECG variables from the data. The model with the best fit had a cp of 0.003 and an accuracy of 79.97%.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">100</span>)</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>treeFit2 <span class="ot">&lt;-</span> <span class="fu">train</span>(HeartDisease <span class="sc">~</span> ., <span class="at">data =</span> heartTrainTransformed2, </span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">method =</span> <span class="st">"rpart"</span>,</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">trControl =</span> heartTrainControl2, </span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">tuneGrid =</span> <span class="fu">expand.grid</span>(<span class="at">cp =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="fl">0.1</span>, <span class="fl">0.001</span>)))</span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a>treeFit2<span class="sc">$</span>results</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       cp  Accuracy     Kappa AccuracySD    KappaSD
1   0.000 0.7974217 0.5870229 0.04278024 0.08798146
2   0.001 0.7974217 0.5870229 0.04278024 0.08798146
3   0.002 0.8015066 0.5949823 0.04187390 0.08613788
4   0.003 0.8019571 0.5958583 0.04174917 0.08590160
5   0.004 0.7960579 0.5838254 0.04261605 0.08745106
6   0.005 0.7915287 0.5752893 0.04263313 0.08661325
7   0.006 0.7856230 0.5638542 0.04633216 0.09408682
8   0.007 0.7770087 0.5462400 0.04435446 0.09011417
9   0.008 0.7770150 0.5465962 0.04387992 0.08877674
10  0.009 0.7801744 0.5531536 0.04357382 0.08858365
11  0.010 0.7824389 0.5583837 0.04107395 0.08307212
12  0.011 0.7892327 0.5721716 0.04092684 0.08165643
13  0.012 0.7887576 0.5712730 0.03957862 0.07964703
14  0.013 0.7896708 0.5736162 0.03970507 0.07974504
15  0.014 0.7933053 0.5812763 0.04105578 0.08218375
16  0.015 0.7946752 0.5844556 0.04130972 0.08269487
17  0.016 0.7946752 0.5844556 0.04130972 0.08269487
18  0.017 0.7946752 0.5844556 0.04130972 0.08269487
19  0.018 0.7946752 0.5844556 0.04130972 0.08269487
20  0.019 0.7946752 0.5844556 0.04130972 0.08269487
21  0.020 0.7946752 0.5844556 0.04130972 0.08269487
22  0.021 0.7932863 0.5818885 0.04257838 0.08514344
23  0.022 0.7932863 0.5818885 0.04257838 0.08514344
24  0.023 0.7923854 0.5802959 0.04248062 0.08504177
25  0.024 0.7919287 0.5794062 0.04237805 0.08485087
26  0.025 0.7919287 0.5794062 0.04237805 0.08485087
27  0.026 0.7919287 0.5794062 0.04237805 0.08485087
28  0.027 0.7919287 0.5794062 0.04237805 0.08485087
29  0.028 0.7923854 0.5804104 0.04323552 0.08671784
30  0.029 0.7923854 0.5804104 0.04323552 0.08671784
31  0.030 0.7923854 0.5804104 0.04323552 0.08671784
32  0.031 0.7923854 0.5804104 0.04323552 0.08671784
33  0.032 0.7923854 0.5804104 0.04323552 0.08671784
34  0.033 0.7923854 0.5804104 0.04323552 0.08671784
35  0.034 0.7896642 0.5753069 0.04595731 0.09170107
36  0.035 0.7896642 0.5753069 0.04595731 0.09170107
37  0.036 0.7896642 0.5753069 0.04595731 0.09170107
38  0.037 0.7896642 0.5753069 0.04595731 0.09170107
39  0.038 0.7860359 0.5686670 0.04880446 0.09701877
40  0.039 0.7860359 0.5686670 0.04880446 0.09701877
41  0.040 0.7860359 0.5686670 0.04880446 0.09701877
42  0.041 0.7824012 0.5622764 0.04688279 0.09331750
43  0.042 0.7824012 0.5622764 0.04688279 0.09331750
44  0.043 0.7824012 0.5622764 0.04688279 0.09331750
45  0.044 0.7824012 0.5622764 0.04688279 0.09331750
46  0.045 0.7824012 0.5624403 0.04688279 0.09331462
47  0.046 0.7824012 0.5624403 0.04688279 0.09331462
48  0.047 0.7824012 0.5624403 0.04688279 0.09331462
49  0.048 0.7846597 0.5675788 0.04801399 0.09579789
50  0.049 0.7846597 0.5675788 0.04801399 0.09579789
51  0.050 0.7846597 0.5675788 0.04801399 0.09579789
52  0.051 0.7846597 0.5675788 0.04801399 0.09579789
53  0.052 0.7846597 0.5675788 0.04801399 0.09579789
54  0.053 0.7846597 0.5675788 0.04801399 0.09579789
55  0.054 0.7846597 0.5675788 0.04801399 0.09579789
56  0.055 0.7846597 0.5675788 0.04801399 0.09579789
57  0.056 0.7846597 0.5675788 0.04801399 0.09579789
58  0.057 0.7846597 0.5675788 0.04801399 0.09579789
59  0.058 0.7846597 0.5675788 0.04801399 0.09579789
60  0.059 0.7846597 0.5675788 0.04801399 0.09579789
61  0.060 0.7846597 0.5675788 0.04801399 0.09579789
62  0.061 0.7846597 0.5675788 0.04801399 0.09579789
63  0.062 0.7846597 0.5675788 0.04801399 0.09579789
64  0.063 0.7846597 0.5675788 0.04801399 0.09579789
65  0.064 0.7846597 0.5675788 0.04801399 0.09579789
66  0.065 0.7846597 0.5675788 0.04801399 0.09579789
67  0.066 0.7846597 0.5675788 0.04801399 0.09579789
68  0.067 0.7846597 0.5675788 0.04801399 0.09579789
69  0.068 0.7846597 0.5675788 0.04801399 0.09579789
70  0.069 0.7846597 0.5675788 0.04801399 0.09579789
71  0.070 0.7846597 0.5675788 0.04801399 0.09579789
72  0.071 0.7846597 0.5675788 0.04801399 0.09579789
73  0.072 0.7846597 0.5675788 0.04801399 0.09579789
74  0.073 0.7846597 0.5675788 0.04801399 0.09579789
75  0.074 0.7846597 0.5675788 0.04801399 0.09579789
76  0.075 0.7846597 0.5675788 0.04801399 0.09579789
77  0.076 0.7846597 0.5675788 0.04801399 0.09579789
78  0.077 0.7846597 0.5675788 0.04801399 0.09579789
79  0.078 0.7846597 0.5675788 0.04801399 0.09579789
80  0.079 0.7846597 0.5675788 0.04801399 0.09579789
81  0.080 0.7846597 0.5675788 0.04801399 0.09579789
82  0.081 0.7846597 0.5675788 0.04801399 0.09579789
83  0.082 0.7846597 0.5675788 0.04801399 0.09579789
84  0.083 0.7846597 0.5675788 0.04801399 0.09579789
85  0.084 0.7846597 0.5675788 0.04801399 0.09579789
86  0.085 0.7846597 0.5675788 0.04801399 0.09579789
87  0.086 0.7846597 0.5675788 0.04801399 0.09579789
88  0.087 0.7846597 0.5675788 0.04801399 0.09579789
89  0.088 0.7846597 0.5675788 0.04801399 0.09579789
90  0.089 0.7846597 0.5675788 0.04801399 0.09579789
91  0.090 0.7846597 0.5675788 0.04801399 0.09579789
92  0.091 0.7846597 0.5675788 0.04801399 0.09579789
93  0.092 0.7846597 0.5675788 0.04801399 0.09579789
94  0.093 0.7846597 0.5675788 0.04801399 0.09579789
95  0.094 0.7846597 0.5675788 0.04801399 0.09579789
96  0.095 0.7846597 0.5675788 0.04801399 0.09579789
97  0.096 0.7846597 0.5675788 0.04801399 0.09579789
98  0.097 0.7846597 0.5675788 0.04801399 0.09579789
99  0.098 0.7846597 0.5675788 0.04801399 0.09579789
100 0.099 0.7846597 0.5675788 0.04801399 0.09579789
101 0.100 0.7846597 0.5675788 0.04801399 0.09579789</code></pre>
</div>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>treeFit2<span class="sc">$</span>bestTune</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     cp
4 0.003</code></pre>
</div>
</div>
<p>Of the 3 models, model 2 had the best accuracy at 80.20%. The confusion matrix output is presented below. The accuracy using test data is 83.61%.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confusionMatrix</span>(<span class="at">data =</span> heartTestTransformed2<span class="sc">$</span>HeartDisease, </span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">reference =</span> <span class="fu">predict</span>(treeFit2, <span class="at">newdata =</span> heartTestTransformed2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction  0  1
         0 63 19
         1 11 90
                                          
               Accuracy : 0.8361          
                 95% CI : (0.7743, 0.8866)
    No Information Rate : 0.5956          
    P-Value [Acc &gt; NIR] : 1.888e-12       
                                          
                  Kappa : 0.6655          
                                          
 Mcnemar's Test P-Value : 0.2012          
                                          
            Sensitivity : 0.8514          
            Specificity : 0.8257          
         Pos Pred Value : 0.7683          
         Neg Pred Value : 0.8911          
             Prevalence : 0.4044          
         Detection Rate : 0.3443          
   Detection Prevalence : 0.4481          
      Balanced Accuracy : 0.8385          
                                          
       'Positive' Class : 0               
                                          </code></pre>
</div>
</div>
</section>
<section id="random-forest" class="level3">
<h3 class="anchored" data-anchor-id="random-forest">Random Forest</h3>
<p>The code and output for model 1 where the Cholesterol variable is removed is presented below. Since this is model 1, we will use heartTrainControl1 from the previous two sections, which used repeatedcv (cross validation), 10 folds and 3 repeats. Since this is for a random forest, we use “rf” for method. The tuning parameter is mtry, which specifies the number of predictors in the data to be randomly sampled at each split. For model 1, we have 10 predictors, so mtry is a data frame of 1:10. The best model for model 1 is the one with an mtry of 2 variables, with an accuracy of 82.52%.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">100</span>)</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>rfFit1 <span class="ot">&lt;-</span> <span class="fu">train</span>(HeartDisease <span class="sc">~</span> ., <span class="at">data =</span> heartTrainTransformed, </span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">method =</span> <span class="st">"rf"</span>,</span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">trControl =</span> heartTrainControl1, </span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">tuneGrid =</span> <span class="fu">data.frame</span>(<span class="at">mtry =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>))</span>
<span id="cb67-6"><a href="#cb67-6" aria-hidden="true" tabindex="-1"></a>rfFit1<span class="sc">$</span>results</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   mtry  Accuracy     Kappa AccuracySD    KappaSD
1     1 0.8133169 0.6205232 0.04080770 0.08362225
2     2 0.8251645 0.6466972 0.04208647 0.08484608
3     3 0.8233691 0.6419224 0.03580293 0.07232984
4     4 0.8178584 0.6309967 0.03455927 0.06908260
5     5 0.8201599 0.6353787 0.03477977 0.06995916
6     6 0.8160818 0.6271489 0.03475278 0.07000140
7     7 0.8115149 0.6180277 0.03464980 0.06905289
8     8 0.8101638 0.6154270 0.03341898 0.06686043
9     9 0.8065046 0.6076599 0.03510831 0.07037622
10   10 0.8001423 0.5951327 0.03515418 0.07068520</code></pre>
</div>
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>rfFit1<span class="sc">$</span>bestTune</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  mtry
2    2</code></pre>
</div>
</div>
<p>The fit for model 2, with mtry of 9, since we are dropping the RestingBP variable for this model, is presented below. A mtry of 2 was also selected for this model, with an accuracy of 82.06%.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">100</span>)</span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>rfFit2 <span class="ot">&lt;-</span> <span class="fu">train</span>(HeartDisease <span class="sc">~</span> ., <span class="at">data =</span> heartTrainTransformed2, </span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">method =</span> <span class="st">"rf"</span>,</span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">trControl =</span> heartTrainControl2, </span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">tuneGrid =</span> <span class="fu">data.frame</span>(<span class="at">mtry =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">9</span>))</span>
<span id="cb71-6"><a href="#cb71-6" aria-hidden="true" tabindex="-1"></a>rfFit2<span class="sc">$</span>results</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  mtry  Accuracy     Kappa AccuracySD    KappaSD
1    1 0.8174646 0.6291965 0.04363995 0.09005835
2    2 0.8206232 0.6382218 0.04381688 0.08790541
3    3 0.8124842 0.6209813 0.03929718 0.07837967
4    4 0.8079053 0.6109714 0.04387788 0.08769356
5    5 0.8056469 0.6063305 0.04269600 0.08602755
6    6 0.8029197 0.6005207 0.04030779 0.08114116
7    7 0.7970268 0.5887011 0.04253811 0.08546944
8    8 0.7974462 0.5897933 0.03823099 0.07659990
9    9 0.7983471 0.5912023 0.04248587 0.08488424</code></pre>
</div>
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>rfFit2<span class="sc">$</span>bestTune</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  mtry
2    2</code></pre>
</div>
</div>
<p>The fit for model 3, with mtry of 8, since we are dropping the RestingECG variable for this model, is presented below. The model with an mtry of 1 gave the highest accuracy, which as 82.02%.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">100</span>)</span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>rfFit3 <span class="ot">&lt;-</span> <span class="fu">train</span>(HeartDisease <span class="sc">~</span> ., <span class="at">data =</span> heartTrainTransformed3, </span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">method =</span> <span class="st">"rf"</span>,</span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">trControl =</span> heartTrainControl3, </span>
<span id="cb75-5"><a href="#cb75-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">tuneGrid =</span> <span class="fu">data.frame</span>(<span class="at">mtry =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">8</span>))</span>
<span id="cb75-6"><a href="#cb75-6" aria-hidden="true" tabindex="-1"></a>rfFit3<span class="sc">$</span>results</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  mtry  Accuracy     Kappa AccuracySD    KappaSD
1    1 0.8201727 0.6362198 0.04853444 0.09879635
2    2 0.8192780 0.6352948 0.04601381 0.09237274
3    3 0.8120213 0.6196776 0.04311814 0.08620577
4    4 0.8028947 0.6005093 0.04381189 0.08788677
5    5 0.7969895 0.5884186 0.04151354 0.08393799
6    6 0.7929107 0.5802062 0.04072806 0.08231423
7    7 0.7851665 0.5643443 0.04004483 0.08078150
8    8 0.7856293 0.5650128 0.04385776 0.08842402</code></pre>
</div>
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>rfFit3<span class="sc">$</span>bestTune</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  mtry
1    1</code></pre>
</div>
</div>
<p>Of the 3 random forest models above, the first model with all predictors except Cholesterol performed the best. The confusion matrix output is presented below for this model. The performance on the test data set was 83.61% accuracy.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confusionMatrix</span>(<span class="at">data =</span> heartTestTransformed<span class="sc">$</span>HeartDisease, </span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">reference =</span> <span class="fu">predict</span>(rfFit1, <span class="at">newdata =</span> heartTestTransformed))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction  0  1
         0 64 18
         1 12 89
                                          
               Accuracy : 0.8361          
                 95% CI : (0.7743, 0.8866)
    No Information Rate : 0.5847          
    P-Value [Acc &gt; NIR] : 2.43e-13        
                                          
                  Kappa : 0.6663          
                                          
 Mcnemar's Test P-Value : 0.3613          
                                          
            Sensitivity : 0.8421          
            Specificity : 0.8318          
         Pos Pred Value : 0.7805          
         Neg Pred Value : 0.8812          
             Prevalence : 0.4153          
         Detection Rate : 0.3497          
   Detection Prevalence : 0.4481          
      Balanced Accuracy : 0.8369          
                                          
       'Positive' Class : 0               
                                          </code></pre>
</div>
</div>
</section>
<section id="boosted-tree" class="level3">
<h3 class="anchored" data-anchor-id="boosted-tree">Boosted Tree</h3>
<p>The same transformed sets used in the previous sections will be used here. For boosted trees, we will use gbm for the method. Since we want to test variations of tuning parameters, a grid with these parameters will be created using expand.grid and this data frame will then be used in tuneGrid. The best model used n.trees of 25 and an interaction depth of 3. The accuracy of this model is 82.33%.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a>grid <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">n.trees =</span> <span class="fu">c</span>(<span class="dv">25</span>,<span class="dv">50</span>, <span class="dv">100</span>, <span class="dv">200</span>), </span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">interaction.depth =</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>), </span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">shrinkage =</span> <span class="fu">c</span>(<span class="fl">0.1</span>), </span>
<span id="cb81-4"><a href="#cb81-4" aria-hidden="true" tabindex="-1"></a>                    <span class="at">n.minobsinnode =</span> <span class="fu">c</span>(<span class="dv">10</span>))</span>
<span id="cb81-5"><a href="#cb81-5" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">100</span>)</span>
<span id="cb81-6"><a href="#cb81-6" aria-hidden="true" tabindex="-1"></a>boostFit1 <span class="ot">&lt;-</span> <span class="fu">train</span>(HeartDisease <span class="sc">~</span> ., <span class="at">data =</span> heartTrainTransformed, </span>
<span id="cb81-7"><a href="#cb81-7" aria-hidden="true" tabindex="-1"></a>                  <span class="at">method =</span> <span class="st">"gbm"</span>,</span>
<span id="cb81-8"><a href="#cb81-8" aria-hidden="true" tabindex="-1"></a>                  <span class="at">trControl =</span> heartTrainControl1, </span>
<span id="cb81-9"><a href="#cb81-9" aria-hidden="true" tabindex="-1"></a>                  <span class="at">tuneGrid =</span> grid, <span class="at">verbose =</span> <span class="cn">FALSE</span>)</span>
<span id="cb81-10"><a href="#cb81-10" aria-hidden="true" tabindex="-1"></a>boostFit1<span class="sc">$</span>results</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   shrinkage interaction.depth n.minobsinnode n.trees  Accuracy     Kappa
1        0.1                 1             10      25 0.7928727 0.5806417
5        0.1                 2             10      25 0.8069234 0.6079759
9        0.1                 3             10      25 0.8233257 0.6413758
2        0.1                 1             10      50 0.8137237 0.6226437
6        0.1                 2             10      50 0.8214934 0.6380441
10       0.1                 3             10      50 0.8215613 0.6385052
3        0.1                 1             10     100 0.8205673 0.6369787
7        0.1                 2             10     100 0.8183084 0.6316129
11       0.1                 3             10     100 0.8224435 0.6399704
4        0.1                 1             10     200 0.8178770 0.6314330
8        0.1                 2             10     200 0.8146741 0.6244337
12       0.1                 3             10     200 0.8128851 0.6209737
   AccuracySD    KappaSD
1  0.04943801 0.10070863
5  0.04995882 0.10192840
9  0.04533459 0.09263861
2  0.04787013 0.09835523
6  0.04721135 0.09695721
10 0.03881041 0.07925127
3  0.04700795 0.09560616
7  0.04919366 0.10042691
11 0.03972635 0.08114557
4  0.05021313 0.10260911
8  0.04537719 0.09316380
12 0.04167730 0.08487011</code></pre>
</div>
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a>boostFit1<span class="sc">$</span>bestTune</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  n.trees interaction.depth shrinkage n.minobsinnode
9      25                 3       0.1             10</code></pre>
</div>
</div>
<p>The output for model 2 is presented below. The optimal settings were for 100 trees and an interaction depth of 2. The accuracy of this model is 82.47%.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">100</span>)</span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a>boostFit2 <span class="ot">&lt;-</span> <span class="fu">train</span>(HeartDisease <span class="sc">~</span> ., <span class="at">data =</span> heartTrainTransformed2, </span>
<span id="cb85-3"><a href="#cb85-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">method =</span> <span class="st">"gbm"</span>,</span>
<span id="cb85-4"><a href="#cb85-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">trControl =</span> heartTrainControl2, </span>
<span id="cb85-5"><a href="#cb85-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">tuneGrid =</span> grid, <span class="at">verbose =</span> <span class="cn">FALSE</span>)</span>
<span id="cb85-6"><a href="#cb85-6" aria-hidden="true" tabindex="-1"></a>boostFit2<span class="sc">$</span>results</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   shrinkage interaction.depth n.minobsinnode n.trees  Accuracy     Kappa
1        0.1                 1             10      25 0.7928727 0.5806417
5        0.1                 2             10      25 0.8092130 0.6127782
9        0.1                 3             10      25 0.8187595 0.6321203
2        0.1                 1             10      50 0.8132919 0.6218593
6        0.1                 2             10      50 0.8187905 0.6325275
10       0.1                 3             10      50 0.8192593 0.6334945
3        0.1                 1             10     100 0.8224005 0.6405965
7        0.1                 2             10     100 0.8246898 0.6443546
11       0.1                 3             10     100 0.8174018 0.6296192
4        0.1                 1             10     200 0.8224373 0.6406566
8        0.1                 2             10     200 0.8137547 0.6219810
12       0.1                 3             10     200 0.8165323 0.6274472
   AccuracySD    KappaSD
1  0.04943801 0.10070863
5  0.05032154 0.10275455
9  0.04583552 0.09360434
2  0.04746243 0.09773845
6  0.04488901 0.09207809
10 0.03972563 0.08100211
3  0.04314156 0.08797859
7  0.04352733 0.08943376
11 0.03883816 0.07929034
4  0.04302682 0.08796330
8  0.04127571 0.08402558
12 0.03796807 0.07736901</code></pre>
</div>
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a>boostFit2<span class="sc">$</span>bestTune</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  n.trees interaction.depth shrinkage n.minobsinnode
7     100                 2       0.1             10</code></pre>
</div>
</div>
<p>The output for model 3 is presented below. The optimal settings were for 100 trees and an interaction depth of 2. The accuracy of this model is 82.56%.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">100</span>)</span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a>boostFit3 <span class="ot">&lt;-</span> <span class="fu">train</span>(HeartDisease <span class="sc">~</span> ., <span class="at">data =</span> heartTrainTransformed3, </span>
<span id="cb89-3"><a href="#cb89-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">method =</span> <span class="st">"gbm"</span>,</span>
<span id="cb89-4"><a href="#cb89-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">trControl =</span> heartTrainControl3, </span>
<span id="cb89-5"><a href="#cb89-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">tuneGrid =</span> grid, <span class="at">verbose =</span> <span class="cn">FALSE</span>)</span>
<span id="cb89-6"><a href="#cb89-6" aria-hidden="true" tabindex="-1"></a>boostFit3<span class="sc">$</span>results</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   shrinkage interaction.depth n.minobsinnode n.trees  Accuracy     Kappa
1        0.1                 1             10      25 0.7928727 0.5806417
5        0.1                 2             10      25 0.8096634 0.6137357
9        0.1                 3             10      25 0.8192161 0.6329016
2        0.1                 1             10      50 0.8132919 0.6218593
6        0.1                 2             10      50 0.8183339 0.6316349
10       0.1                 3             10      50 0.8206294 0.6364518
3        0.1                 1             10     100 0.8228571 0.6414965
7        0.1                 2             10     100 0.8256213 0.6468173
11       0.1                 3             10     100 0.8197283 0.6342570
4        0.1                 1             10     200 0.8229001 0.6416137
8        0.1                 2             10     200 0.8124407 0.6193236
12       0.1                 3             10     200 0.8142987 0.6221569
   AccuracySD    KappaSD
1  0.04943801 0.10070863
5  0.05002051 0.10212444
9  0.04649623 0.09512165
2  0.04746243 0.09773845
6  0.04434589 0.09101890
10 0.03951869 0.08031833
3  0.04305870 0.08780468
7  0.04414476 0.09021264
11 0.04123607 0.08455477
4  0.04365448 0.08922363
8  0.03836767 0.07827551
12 0.04270759 0.08776276</code></pre>
</div>
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a>boostFit3<span class="sc">$</span>bestTune</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  n.trees interaction.depth shrinkage n.minobsinnode
7     100                 2       0.1             10</code></pre>
</div>
</div>
<p>Of the 3 models, model 3 gave the best accuracy. The confusion matrix is below. The accuracy on the test data is 83.06%.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confusionMatrix</span>(<span class="at">data =</span> heartTestTransformed3<span class="sc">$</span>HeartDisease, </span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">reference =</span> <span class="fu">predict</span>(boostFit3, <span class="at">newdata =</span> heartTestTransformed3))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction  0  1
         0 65 17
         1 14 87
                                          
               Accuracy : 0.8306          
                 95% CI : (0.7683, 0.8819)
    No Information Rate : 0.5683          
    P-Value [Acc &gt; NIR] : 3.715e-14       
                                          
                  Kappa : 0.6563          
                                          
 Mcnemar's Test P-Value : 0.7194          
                                          
            Sensitivity : 0.8228          
            Specificity : 0.8365          
         Pos Pred Value : 0.7927          
         Neg Pred Value : 0.8614          
             Prevalence : 0.4317          
         Detection Rate : 0.3552          
   Detection Prevalence : 0.4481          
      Balanced Accuracy : 0.8297          
                                          
       'Positive' Class : 0               
                                          </code></pre>
</div>
</div>
</section>
</section>
<section id="wrap-up" class="level2">
<h2 class="anchored" data-anchor-id="wrap-up">Wrap Up</h2>
<p>KNN and the best performing logistic regression model both had an accuracy of 81.97% on the test data. Similarly, the best classification tree and random forest model had an accuracy of 83.61% on the test data. Lastly, the boosted tree had an accuracy of 83.06% for the test data. In conclusion, there was a tie between the classification tree and random forest models for best performer, with both having an accuracy of 83.61% on the test set. However, the random forest model with the best accuracy used 10 variables while the classification model used 9. Since we usually want to use the most parsimonious model, the classification model may be the better option of the two.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>